Justin
robinschiro/OS_Group53 pull request #6
Opened 2017-02-09 06:07 UTC by AtreidesUCF

2017-02-10 17:49 UTC, robinschiro requested changes
I found a serious issue in your implementation (look at comment on line 457). You should be using a "ready" queue to keep track of which process to select next. 

The test cases I made (in the "custom-tests" folder on the master branch) should help verify the correctness of your implementation.

2017-02-10 17:49 UTC, robinschiro commented on Scheduler/main.c
> +               printProcessSelected(time, &processes[i]);
If there is only one ready process for multiple quantums, then the same selection will be printed multiple times. Selection should only be printed when a new process is selected (look at runSFJ() for an example of this)

2017-02-10 17:49 UTC, robinschiro commented on Scheduler/main.c
> +
Be sure to check if the current process is finished at this time step (same comment I made for Khoa).

2017-02-10 17:49 UTC, robinschiro commented on Scheduler/main.c
> +            if (processes[i].isReady)
I see that when you're selecting the next process to process, you are iterating though ready processes in the order that they appear in the 'processes' array (that is, in the order that we parsed the file). According to our notes (Lecture 1.3), they should be selected based on the implementation of a "ready" queue. A process is enqueued on the ready_queue when it arrives and when it is deselected. It is dequeued when it is selected.

2017-02-10 22:19 UTC, AtreidesUCF commented on Scheduler/main.c
> +
Fixed

2017-02-11 01:13 UTC, robinschiro approved these changes
Looks good!

2017-02-11 01:14 UTC, merged